server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
  servlet:
    context-path: /api/v1.0
  port: 8080
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      location: java.io.tmpdir
      max-file-size: 100MB
